---
title: "Mini-Project 2"
author: "Zoya and Ruth"
date: "March 20, 2019"
output:
  html_document:
    code_folding: hide
---

##Voter turnout for House of Representative candidates, as a national proportion
s
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
```

```{r message = FALSE, warning=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r message = FALSE, warning=FALSE}

#Get data for primary votes per candidate, candidate office and candidate state in one table
table1 <- candidates %>%
  full_join(house_elections, by = c("cand_id" = "fec_id")) %>%
  filter(cand_office == "H") %>%
  select(cand_id,cand_name,cand_state,primary_votes,party) %>%
  filter(!is.na(primary_votes))
#note that we filtered out all folks running for House, who had missing data for primary votes
#originally 4160 candidates
#missing data brought it down to 2157
```

```{r message=FALSE, warning=FALSE}
#create table with total primary votes per state
table2 <- table1 %>%
  group_by(cand_state) %>%
  summarise(total_state_vote = sum(primary_votes))
```

```{r}
#find out how many total votes in our dataframe
table3 <- table2 %>% 
  mutate(proportion = total_state_vote/sum(total_state_vote))
  #filter(proportion > 0.50) #filter according to the percentage political scientists consider good voter turnout
```

```{r}
graph1 <- ggplot(table3, aes(x = cand_state, y = proportion)) +
  geom_col(fill="purple", alpha = 0.5) 
graph1
```


#Importing state population from excel
```{r}
state_population <- read.csv("state_population.csv")
```


```{r}
population_data <- state_population %>%
  rename(cand_state=table.with.row.headers.in.column.A.and.column.headers.in.rows.3.through.4...leading.dots.indicate.sub.parts., "2011"= X, "2012"=X.1)

avg <- population_data %>%
  avg <- c("2011","2012")

population_data %>%
  mutate(avg_st_pop= mean(avg))
```

```{r}
#r wordcountaddin::word_count()
```

